apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: etbp2oj1j-go 
  janus-idp.io/tekton: etbp2oj1j-go
  backstage.io/kubernetes-id: etbp2oj1j-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: etbp2oj1j-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  